import type { Metadata } from "next";
import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";

import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Toaster } from "sonner";
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-serif",
});
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "300"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Forge -AI App Builder",
  description: "Generated by create next app",
  icons :{
    icon:"/logo-short-removebg-preview.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html
      lang="en"
      className={cn(
       
      )}
      suppressHydrationWarning
      suppressContentEditableWarning
    >
      <body className={`${lora.variable} ${dmSans.variable} font-sans`}>
           <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header  />  
              

            <main>  {children}</main>
          
          <Toaster richColors/>
          </ThemeProvider></body>
    </html></ClerkProvider>
  );
}
